#! /bin/sh

sxhkd &

# Monitor configuration
hdmi_connected=`xrandr | grep HDMI`

if [ -z "$hdmi_connected" ]; then
    echo "no hay monitor"
else
    hdmi_resolution=`xrandr | grep -A 1 "HDMI" | grep -oP "[0-9]+x[0-9]+\s"`
    case "$hdmi_resolution" in 
        "3840x2160 ")
            `~/.screenlayout/4k_eDP.sh`
            ;;
        "1920x1080 ")
            `~/.screenlayout/hd_eDP.sh`
            ;;
        *)
            echo "sepa puta"
    esac
fi

bspc monitor eDP-1-1 -d I II III IV
bspc monitor HDMI-1-1 -d V VI VII VIII

bspc config active_border_color '#5E8D87'
bspc config normal_border_color '#707880'
bspc config focused_border_color '#8ABEB7'

bspc config border_width         4
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config top_padding 27
bspc config left_padding 5
bspc config right_padding 5

$HOME/.config/polybar/launch.sh &

compton -Ccb
feh --bg-fill ~/Pictures/Wallpaper/wallhaven-4gq6yd.jpg
